[package]
name = "cachem_example"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies]
async-trait = "0.1.42"
cachem_utils = { path = "../utils", features = ["derive", "with-uuid"] }
tokio = { version = "1.1.1", features = ["full"] }
