[package]
name = "cachem_example"
authors = ["Lars Holznagel <contact@lholznagel.info>"]
version = "0.1.0"
edition = "2018"

[dependencies]
async-trait = "0.1.42"
cachem = { path = "../cachem", features = ["derive", "with-uuid"] }
tokio = { version = "1.1.1", features = ["full"] }
