[package]
name = "cachem_derive"
version = "0.1.0"
authors = ["Lars Holznagel <contact@lholznagel.info>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["extra-traits", "full"] }

[dev-dependencies]
async-trait = "0.1.42"
tokio = { version = "1.1.1", features = ["full"] }
