[package]
name = "cachem_utils"
version = "0.0.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
async-trait = "0.1.42"
cachem_derive = { path = "../derive" }
tokio = { version = "1.0.2", features = ["full"] }
